version: "3"

services:
  ros_melodic:
    image: my_ros_container  # Explicitly specify the image name
    container_name: ros_melodic_container
    volumes:
      - ./catkin_ws:/root/catkin_ws
      - /tmp/.X11-unix:/tmp/.X11-unix  # Mount the X11 socket for GUI support
    ports:
      - "11311:11311"
    environment:
      - DISPLAY=$DISPLAY  # Pass the host display to the container
      - QT_X11_NO_MITSHM=1  # Prevent shared memory issues with Qt applications
    devices:
      - "/dev/video0:/dev/video0"  # Map video devices
    runtime: nvidia  # Use NVIDIA runtime for GPU support
    networks:
      - ros_network
    command: /bin/bash -c "while true; do sleep 1000; done"  # Keeps the container running
    stdin_open: true  # Open stdin to keep it interactive
    tty: true  # Allocate a pseudo-TTY so you can interact with the shell

networks:
  ros_network:
    driver: bridge
